---
name: General entry type
desc: A schema used by all supported entry types
type: map
mapping:
  type:
    type: str
    enum: ['PARTY', 'REGIONAL_CHAPTER', 'COMMITTEE', 'YOUTH_ORGANIZATION']
    required: true
  country:
    type: str
  urls:
    type: seq
    sequence:
      - type: map
        mapping:
          type:
            type: str
            pattern: '^[A-Z]+$'
          url:
            type: str
            pattern: '^(http|https)://[\.a-z-]+[a-zA-Z0-9\.\/\_\-\+\%\#\@]*$'
  emails:
    type: seq
    sequence:
      - type: map
        mapping:
          address:
            type: str
            pattern: '^.+@.+$'
  level:
    type: str
    required: true
    enum: ['DE:BUNDESVERBAND', 'DE:LANDESVERBAND', 'DE:REGIONALVERBAND',
           'DE:KREISVERBAND', 'DE:BEZIRKSVERBAND', 'DE:ORTSVERBAND']
  state:
    type: str
  region:
    type: str
  district:
    type: str
  city:
    type: str
